name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  modal_progress_hud: ^0.1.3
  font_awesome_flutter: ^8.8.1
  url_launcher:
  shared_preferences:
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/logo.png
    - images/HPLogo.png
    - images/doctor.png
    - images/hospital.png
    - images/ambulance.png
    - images/clinic.png
    - images/statistics.png
    - images/calculator.png
    - images/covidImage.png
    - images/AMCLtd.jpg
    - images/BDENTHospital.jpg
    - images/CityHospital.jpg
    - images/EvercareHospital.jpg
    - images/IbnSinaHospital.jpg
    - images/PediatricHospital.jpg
    - images/Labaid-ambulance.png
    - images/AlAminAmbulance.jpg
    - images/alif-ambulence-service.jpg
    - images/TraumaCenterAmbulance.jpg
    - images/Ad-dinAmbulance.jpg
    - images/kingston-ambulance.jpg
    - images/listhospital.png
